### ISSUE TITLE
How can i get my aidungeon story on the website

### ISSUE THREAD

**Issue by Queef-star** [CoomersGuide/CoomersGuide.github.io#16]
I want to make my storyy that i made with aidungeon to on the website but how can i get it do that?

also is fanfiction allowed or is it illegal

https://witchersaiyan.neocities.org/witchersaiyan.pdf

**Comment by CoomerDeveloper** [comment]
/aidg/ stories page is up now, your story is there, among others.

<https://guide.aidg.club/Resources-And-Guides/Stories/aidg-stories.html>
